export const CONFIG_DISCORD_NAME_KEY = "DISCORD_NAME";
export const CHROME_NOTIFICATION_KEY = "NEGUKO_NOTIFICATION";
export const SUCCEED_MESSAGE = "再生依頼に成功したぞ！";
export const SUCCEED_MESSAGE_TIMEOUT = 2000;
