name: Build extension

on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: neg-youtube
          path: "./dist"
          if-no-files-found: error
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "新しいねぐ子の拡張機能がリリースされました！\nダウンロード: ${{ steps.artifact-upload.outputs.artifact-url }}"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
